services:
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:80'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules