FROM node:14-buster-slim as build

WORKDIR /app

ADD package.json package.json

RUN npm install

ADD . .

RUN npm run build

FROM nginx:1.21.0-alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]